/*
 * A header file for a class that writes a single triangular Postscript dot
 * plot. More precisely, the dot plots generated by this class are backed by
 * an RNA object.
 *
 * Copyright 2010 Mathews Lab, University of Rochester
 * Written by Jessica S. Reuter
 */

#include "Postscript_Single_Plot.h"

///////////////////////////////////////////////////////////////////////////////
// Constructor
///////////////////////////////////////////////////////////////////////////////
Postscript_Single_Plot::Postscript_Single_Plot( DotPlotHandler* handler,
						int type )
  : Postscript_Dot_Plot( handler ) {

  // Create the RNA strand.
  strand = new RNA( handler->getInputFile().c_str(), type );

  // Initialize the error checker and sequence length.
  initializeStrandHelpers();

}

///////////////////////////////////////////////////////////////////////////////
// Destructor
///////////////////////////////////////////////////////////////////////////////
Postscript_Single_Plot::~Postscript_Single_Plot() {}

