/*
 * A header file for a class that writes a single triangular Postscript dot
 * plot. More precisely, the dot plots generated by this class are backed by
 * an RNA object.
 *
 * Copyright 2010 Mathews Lab, University of Rochester
 * Written by Jessica S. Reuter
 */

#ifndef POSTSCRIPT_SINGLE_PLOT_H
#define POSTSCRIPT_SINGLE_PLOT_H

#include "Postscript_Dot_Plot.h"

class Postscript_Single_Plot : public Postscript_Dot_Plot {
 protected:
  // Protected constructor and destructor.

  /*
   * Name:        Constructor
   * Description: Constructor which initializes the RNA data structure for this
   *              class directly, creating the RNA object inside itself.
   *              Also, initializes private variables.
   * Arguments:
   *     1. handler
   *        The dot plot handler that holds data.
   *     2. type
   *        The type of dot plot to create.
   */
  Postscript_Single_Plot( DotPlotHandler* handler, int type );

  /*
   * Name:        Destructor
   * Description: Actually does not delete anything, just here as a placeholder
   */
  virtual ~Postscript_Single_Plot();
};

#endif /* POSTSCRIPT_SINGLE_PLOT_H */
