/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public class DotPlotHandler {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DotPlotHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DotPlotHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      DotPlotHandlerProxyJNI.delete_DotPlotHandler(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DotPlotHandler(String inFile, String outFile) {
    this(DotPlotHandlerProxyJNI.new_DotPlotHandler(inFile, outFile), true);
  }

  public String getColorAsPostscript(int i, int j) {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getColorAsPostscript(swigCPtr, this, i, j);
  }

  public String getColorAsRGB(int i, int j) {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getColorAsRGB(swigCPtr, this, i, j);
  }

  public int getEntries() {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getEntries(swigCPtr, this);
  }

  public String getInfoString() {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getInfoString(swigCPtr, this);
  }

  public String getInputFile() {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getInputFile(swigCPtr, this);
  }

  public double getMaximum() {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getMaximum(swigCPtr, this);
  }

  public double getMinimum() {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getMinimum(swigCPtr, this);
  }

  public String getOutputFile() {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getOutputFile(swigCPtr, this);
  }

  public char getPlotType() {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getPlotType(swigCPtr, this);
  }

  public double getValue(int i, int j) {
    return DotPlotHandlerProxyJNI.DotPlotHandler_getValue(swigCPtr, this, i, j);
  }

  public boolean isError() {
    return DotPlotHandlerProxyJNI.DotPlotHandler_isError(swigCPtr, this);
  }

  public void readDynalignSeq1Data() {
    DotPlotHandlerProxyJNI.DotPlotHandler_readDynalignSeq1Data(swigCPtr, this);
  }

  public void readDynalignSeq2Data() {
    DotPlotHandlerProxyJNI.DotPlotHandler_readDynalignSeq2Data(swigCPtr, this);
  }

  public void readFoldingData() {
    DotPlotHandlerProxyJNI.DotPlotHandler_readFoldingData(swigCPtr, this);
  }

  public void readPartitionData() {
    DotPlotHandlerProxyJNI.DotPlotHandler_readPartitionData(swigCPtr, this);
  }

  public void readTextData() {
    DotPlotHandlerProxyJNI.DotPlotHandler_readTextData(swigCPtr, this);
  }

  public void resetRange() {
    DotPlotHandlerProxyJNI.DotPlotHandler_resetRange(swigCPtr, this);
  }

  public void setEntries(int newEntries) {
    DotPlotHandlerProxyJNI.DotPlotHandler_setEntries(swigCPtr, this, newEntries);
  }

  public void setMaximum(double newMaximum) {
    DotPlotHandlerProxyJNI.DotPlotHandler_setMaximum(swigCPtr, this, newMaximum);
  }

  public void setMinimum(double newMinimum) {
    DotPlotHandlerProxyJNI.DotPlotHandler_setMinimum(swigCPtr, this, newMinimum);
  }

  public void setPlotType(char type) {
    DotPlotHandlerProxyJNI.DotPlotHandler_setPlotType(swigCPtr, this, type);
  }

  public void writePlotFile() {
    DotPlotHandlerProxyJNI.DotPlotHandler_writePlotFile(swigCPtr, this);
  }

}
