/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

class DotPlotHandlerProxyJNI {
  public final static native long new_DotPlotHandler(String jarg1, String jarg2);
  public final static native void delete_DotPlotHandler(long jarg1);
  public final static native String DotPlotHandler_getColorAsPostscript(long jarg1, DotPlotHandler jarg1_, int jarg2, int jarg3);
  public final static native String DotPlotHandler_getColorAsRGB(long jarg1, DotPlotHandler jarg1_, int jarg2, int jarg3);
  public final static native int DotPlotHandler_getEntries(long jarg1, DotPlotHandler jarg1_);
  public final static native String DotPlotHandler_getInfoString(long jarg1, DotPlotHandler jarg1_);
  public final static native String DotPlotHandler_getInputFile(long jarg1, DotPlotHandler jarg1_);
  public final static native double DotPlotHandler_getMaximum(long jarg1, DotPlotHandler jarg1_);
  public final static native double DotPlotHandler_getMinimum(long jarg1, DotPlotHandler jarg1_);
  public final static native String DotPlotHandler_getOutputFile(long jarg1, DotPlotHandler jarg1_);
  public final static native char DotPlotHandler_getPlotType(long jarg1, DotPlotHandler jarg1_);
  public final static native double DotPlotHandler_getValue(long jarg1, DotPlotHandler jarg1_, int jarg2, int jarg3);
  public final static native boolean DotPlotHandler_isError(long jarg1, DotPlotHandler jarg1_);
  public final static native void DotPlotHandler_readDynalignSeq1Data(long jarg1, DotPlotHandler jarg1_);
  public final static native void DotPlotHandler_readDynalignSeq2Data(long jarg1, DotPlotHandler jarg1_);
  public final static native void DotPlotHandler_readFoldingData(long jarg1, DotPlotHandler jarg1_);
  public final static native void DotPlotHandler_readPartitionData(long jarg1, DotPlotHandler jarg1_);
  public final static native void DotPlotHandler_readTextData(long jarg1, DotPlotHandler jarg1_);
  public final static native void DotPlotHandler_resetRange(long jarg1, DotPlotHandler jarg1_);
  public final static native void DotPlotHandler_setEntries(long jarg1, DotPlotHandler jarg1_, int jarg2);
  public final static native void DotPlotHandler_setMaximum(long jarg1, DotPlotHandler jarg1_, double jarg2);
  public final static native void DotPlotHandler_setMinimum(long jarg1, DotPlotHandler jarg1_, double jarg2);
  public final static native void DotPlotHandler_setPlotType(long jarg1, DotPlotHandler jarg1_, char jarg2);
  public final static native void DotPlotHandler_writePlotFile(long jarg1, DotPlotHandler jarg1_);
}
