/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public class Dynalign_object extends TwoRNA {
  private long swigCPtr;

  protected Dynalign_object(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Dynalign_object obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      Dynalign_objectProxyJNI.delete_Dynalign_object(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public Dynalign_object() {
    this(Dynalign_objectProxyJNI.new_Dynalign_object__SWIG_0(), true);
  }

  public Dynalign_object(String sequence1, String sequence2, boolean IsRNA) {
    this(Dynalign_objectProxyJNI.new_Dynalign_object__SWIG_1(sequence1, sequence2, IsRNA), true);
  }

  public Dynalign_object(String sequence1, String sequence2) {
    this(Dynalign_objectProxyJNI.new_Dynalign_object__SWIG_2(sequence1, sequence2), true);
  }

  public Dynalign_object(String filename1, int type1, String filename2, int type2, boolean IsRNA) {
    this(Dynalign_objectProxyJNI.new_Dynalign_object__SWIG_3(filename1, type1, filename2, type2, IsRNA), true);
  }

  public Dynalign_object(String filename1, int type1, String filename2, int type2) {
    this(Dynalign_objectProxyJNI.new_Dynalign_object__SWIG_4(filename1, type1, filename2, type2), true);
  }

  public Dynalign_object(String filename) {
    this(Dynalign_objectProxyJNI.new_Dynalign_object__SWIG_5(filename), true);
  }

  public Dynalign_object(String filename, short maxtrace, short bpwin, short awin, short percent) {
    this(Dynalign_objectProxyJNI.new_Dynalign_object__SWIG_6(filename, maxtrace, bpwin, awin, percent), true);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation, float gap, boolean singleinsert, String savefile, boolean optimalonly, short singlefold_subopt_percent, boolean local, short numProcessors, int maxpairs, short cycles) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_0(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation, gap, singleinsert, savefile, optimalonly, singlefold_subopt_percent, local, numProcessors, maxpairs, cycles);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation, float gap, boolean singleinsert, String savefile, boolean optimalonly, short singlefold_subopt_percent, boolean local, short numProcessors, int maxpairs) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_1(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation, gap, singleinsert, savefile, optimalonly, singlefold_subopt_percent, local, numProcessors, maxpairs);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation, float gap, boolean singleinsert, String savefile, boolean optimalonly, short singlefold_subopt_percent, boolean local, short numProcessors) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_2(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation, gap, singleinsert, savefile, optimalonly, singlefold_subopt_percent, local, numProcessors);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation, float gap, boolean singleinsert, String savefile, boolean optimalonly, short singlefold_subopt_percent, boolean local) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_3(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation, gap, singleinsert, savefile, optimalonly, singlefold_subopt_percent, local);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation, float gap, boolean singleinsert, String savefile, boolean optimalonly, short singlefold_subopt_percent) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_4(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation, gap, singleinsert, savefile, optimalonly, singlefold_subopt_percent);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation, float gap, boolean singleinsert, String savefile, boolean optimalonly) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_5(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation, gap, singleinsert, savefile, optimalonly);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation, float gap, boolean singleinsert, String savefile) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_6(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation, gap, singleinsert, savefile);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation, float gap, boolean singleinsert) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_7(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation, gap, singleinsert);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation, float gap) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_8(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation, gap);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent, short imaxseparation) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_9(swigCPtr, this, maxtrace, bpwin, awin, percent, imaxseparation);
  }

  public int Dynalign(short maxtrace, short bpwin, short awin, short percent) {
    return Dynalign_objectProxyJNI.Dynalign_object_Dynalign__SWIG_10(swigCPtr, this, maxtrace, bpwin, awin, percent);
  }

  public void WriteAlignment(String filename) {
    Dynalign_objectProxyJNI.Dynalign_object_WriteAlignment(swigCPtr, this, filename);
  }

  public int ForceAlignment(int i, int k) {
    return Dynalign_objectProxyJNI.Dynalign_object_ForceAlignment(swigCPtr, this, i, k);
  }

  public int GetForcedAlignment(int i, int seq) {
    return Dynalign_objectProxyJNI.Dynalign_object_GetForcedAlignment(swigCPtr, this, i, seq);
  }

  public int ReadAlignmentConstraints(String filename) {
    return Dynalign_objectProxyJNI.Dynalign_object_ReadAlignmentConstraints(swigCPtr, this, filename);
  }

  public int Templatefromct(String ctfilename) {
    return Dynalign_objectProxyJNI.Dynalign_object_Templatefromct(swigCPtr, this, ctfilename);
  }

  public int Templatefromdsv(String dsvfilename, float maxdsvchange) {
    return Dynalign_objectProxyJNI.Dynalign_object_Templatefromdsv(swigCPtr, this, dsvfilename, maxdsvchange);
  }

  public double GetBestPairEnergy(int sequence, int i, int j) {
    return Dynalign_objectProxyJNI.Dynalign_object_GetBestPairEnergy(swigCPtr, this, sequence, i, j);
  }

  public double GetLowestEnergy() {
    return Dynalign_objectProxyJNI.Dynalign_object_GetLowestEnergy(swigCPtr, this);
  }

  public String GetErrorMessage(int error) {
    return Dynalign_objectProxyJNI.Dynalign_object_GetErrorMessage(swigCPtr, this, error);
  }

  public void SetProgress(TProgressDialog Progress) {
    Dynalign_objectProxyJNI.Dynalign_object_SetProgress(swigCPtr, this, TProgressDialog.getCPtr(Progress), Progress);
  }

  public void StopProgress() {
    Dynalign_objectProxyJNI.Dynalign_object_StopProgress(swigCPtr, this);
  }

}
