/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

class Dynalign_objectProxyJNI {
  public final static native long new_Dynalign_object__SWIG_0();
  public final static native long new_Dynalign_object__SWIG_1(String jarg1, String jarg2, boolean jarg3);
  public final static native long new_Dynalign_object__SWIG_2(String jarg1, String jarg2);
  public final static native long new_Dynalign_object__SWIG_3(String jarg1, int jarg2, String jarg3, int jarg4, boolean jarg5);
  public final static native long new_Dynalign_object__SWIG_4(String jarg1, int jarg2, String jarg3, int jarg4);
  public final static native long new_Dynalign_object__SWIG_5(String jarg1);
  public final static native long new_Dynalign_object__SWIG_6(String jarg1, short jarg2, short jarg3, short jarg4, short jarg5);
  public final static native int Dynalign_object_Dynalign__SWIG_0(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6, float jarg7, boolean jarg8, String jarg9, boolean jarg10, short jarg11, boolean jarg12, short jarg13, int jarg14, short jarg15);
  public final static native int Dynalign_object_Dynalign__SWIG_1(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6, float jarg7, boolean jarg8, String jarg9, boolean jarg10, short jarg11, boolean jarg12, short jarg13, int jarg14);
  public final static native int Dynalign_object_Dynalign__SWIG_2(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6, float jarg7, boolean jarg8, String jarg9, boolean jarg10, short jarg11, boolean jarg12, short jarg13);
  public final static native int Dynalign_object_Dynalign__SWIG_3(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6, float jarg7, boolean jarg8, String jarg9, boolean jarg10, short jarg11, boolean jarg12);
  public final static native int Dynalign_object_Dynalign__SWIG_4(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6, float jarg7, boolean jarg8, String jarg9, boolean jarg10, short jarg11);
  public final static native int Dynalign_object_Dynalign__SWIG_5(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6, float jarg7, boolean jarg8, String jarg9, boolean jarg10);
  public final static native int Dynalign_object_Dynalign__SWIG_6(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6, float jarg7, boolean jarg8, String jarg9);
  public final static native int Dynalign_object_Dynalign__SWIG_7(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6, float jarg7, boolean jarg8);
  public final static native int Dynalign_object_Dynalign__SWIG_8(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6, float jarg7);
  public final static native int Dynalign_object_Dynalign__SWIG_9(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5, short jarg6);
  public final static native int Dynalign_object_Dynalign__SWIG_10(long jarg1, Dynalign_object jarg1_, short jarg2, short jarg3, short jarg4, short jarg5);
  public final static native void Dynalign_object_WriteAlignment(long jarg1, Dynalign_object jarg1_, String jarg2);
  public final static native int Dynalign_object_ForceAlignment(long jarg1, Dynalign_object jarg1_, int jarg2, int jarg3);
  public final static native int Dynalign_object_GetForcedAlignment(long jarg1, Dynalign_object jarg1_, int jarg2, int jarg3);
  public final static native int Dynalign_object_ReadAlignmentConstraints(long jarg1, Dynalign_object jarg1_, String jarg2);
  public final static native int Dynalign_object_Templatefromct(long jarg1, Dynalign_object jarg1_, String jarg2);
  public final static native int Dynalign_object_Templatefromdsv(long jarg1, Dynalign_object jarg1_, String jarg2, float jarg3);
  public final static native double Dynalign_object_GetBestPairEnergy(long jarg1, Dynalign_object jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native double Dynalign_object_GetLowestEnergy(long jarg1, Dynalign_object jarg1_);
  public final static native String Dynalign_object_GetErrorMessage(long jarg1, Dynalign_object jarg1_, int jarg2);
  public final static native void Dynalign_object_SetProgress(long jarg1, Dynalign_object jarg1_, long jarg2, TProgressDialog jarg2_);
  public final static native void Dynalign_object_StopProgress(long jarg1, Dynalign_object jarg1_);
  public final static native void delete_Dynalign_object(long jarg1);
  public final static native long SWIGDynalign_objectUpcast(long jarg1);
}
