/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public class HybridRNA extends RNA {
  private long swigCPtr;

  protected HybridRNA(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HybridRNA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      HybridRNAProxyJNI.delete_HybridRNA(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public HybridRNA(String sequence1, String sequence2, boolean IsRNA) {
    this(HybridRNAProxyJNI.new_HybridRNA__SWIG_0(sequence1, sequence2, IsRNA), true);
  }

  public HybridRNA(String sequence1, String sequence2) {
    this(HybridRNAProxyJNI.new_HybridRNA__SWIG_1(sequence1, sequence2), true);
  }

  public HybridRNA(String filename1, int type1, String filename2, int type2, boolean IsRNA) {
    this(HybridRNAProxyJNI.new_HybridRNA__SWIG_2(filename1, type1, filename2, type2, IsRNA), true);
  }

  public HybridRNA(String filename1, int type1, String filename2, int type2) {
    this(HybridRNAProxyJNI.new_HybridRNA__SWIG_3(filename1, type1, filename2, type2), true);
  }

  public int FoldBimolecular(float percent, int maximumstructures, int window, String savefile, int maxinternalloopsize) {
    return HybridRNAProxyJNI.HybridRNA_FoldBimolecular__SWIG_0(swigCPtr, this, percent, maximumstructures, window, savefile, maxinternalloopsize);
  }

  public int FoldBimolecular(float percent, int maximumstructures, int window, String savefile) {
    return HybridRNAProxyJNI.HybridRNA_FoldBimolecular__SWIG_1(swigCPtr, this, percent, maximumstructures, window, savefile);
  }

  public int FoldBimolecular(float percent, int maximumstructures, int window) {
    return HybridRNAProxyJNI.HybridRNA_FoldBimolecular__SWIG_2(swigCPtr, this, percent, maximumstructures, window);
  }

  public int FoldDuplex(float percent, int maximumstructures, int window, int maxinternalloopsize) {
    return HybridRNAProxyJNI.HybridRNA_FoldDuplex__SWIG_0(swigCPtr, this, percent, maximumstructures, window, maxinternalloopsize);
  }

  public int FoldDuplex(float percent, int maximumstructures, int window) {
    return HybridRNAProxyJNI.HybridRNA_FoldDuplex__SWIG_1(swigCPtr, this, percent, maximumstructures, window);
  }

  public int PartitionFunctionBimolecular(String savefile) {
    return HybridRNAProxyJNI.HybridRNA_PartitionFunctionBimolecular__SWIG_0(swigCPtr, this, savefile);
  }

  public int PartitionFunctionBimolecular() {
    return HybridRNAProxyJNI.HybridRNA_PartitionFunctionBimolecular__SWIG_1(swigCPtr, this);
  }

  public RNA GetRNA1() {
    long cPtr = HybridRNAProxyJNI.HybridRNA_GetRNA1(swigCPtr, this);
    return (cPtr == 0) ? null : new RNA(cPtr, false);
  }

  public RNA GetRNA2() {
    long cPtr = HybridRNAProxyJNI.HybridRNA_GetRNA2(swigCPtr, this);
    return (cPtr == 0) ? null : new RNA(cPtr, false);
  }

  public int GetErrorCode() {
    return HybridRNAProxyJNI.HybridRNA_GetErrorCode(swigCPtr, this);
  }

  public String GetErrorMessage(int error) {
    return HybridRNAProxyJNI.HybridRNA_GetErrorMessage(swigCPtr, this, error);
  }

  public boolean GetForbidIntramolecular() {
    return HybridRNAProxyJNI.HybridRNA_GetForbidIntramolecular(swigCPtr, this);
  }

  public void SetForbidIntramolecular(boolean forbid) {
    HybridRNAProxyJNI.HybridRNA_SetForbidIntramolecular(swigCPtr, this, forbid);
  }

  public void SetProgress(TProgressDialog Progress) {
    HybridRNAProxyJNI.HybridRNA_SetProgress(swigCPtr, this, TProgressDialog.getCPtr(Progress), Progress);
  }

  public void StopProgress() {
    HybridRNAProxyJNI.HybridRNA_StopProgress(swigCPtr, this);
  }

}
