/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

class HybridRNAProxyJNI {
  public final static native long new_HybridRNA__SWIG_0(String jarg1, String jarg2, boolean jarg3);
  public final static native long new_HybridRNA__SWIG_1(String jarg1, String jarg2);
  public final static native long new_HybridRNA__SWIG_2(String jarg1, int jarg2, String jarg3, int jarg4, boolean jarg5);
  public final static native long new_HybridRNA__SWIG_3(String jarg1, int jarg2, String jarg3, int jarg4);
  public final static native int HybridRNA_FoldBimolecular__SWIG_0(long jarg1, HybridRNA jarg1_, float jarg2, int jarg3, int jarg4, String jarg5, int jarg6);
  public final static native int HybridRNA_FoldBimolecular__SWIG_1(long jarg1, HybridRNA jarg1_, float jarg2, int jarg3, int jarg4, String jarg5);
  public final static native int HybridRNA_FoldBimolecular__SWIG_2(long jarg1, HybridRNA jarg1_, float jarg2, int jarg3, int jarg4);
  public final static native int HybridRNA_FoldDuplex__SWIG_0(long jarg1, HybridRNA jarg1_, float jarg2, int jarg3, int jarg4, int jarg5);
  public final static native int HybridRNA_FoldDuplex__SWIG_1(long jarg1, HybridRNA jarg1_, float jarg2, int jarg3, int jarg4);
  public final static native int HybridRNA_PartitionFunctionBimolecular__SWIG_0(long jarg1, HybridRNA jarg1_, String jarg2);
  public final static native int HybridRNA_PartitionFunctionBimolecular__SWIG_1(long jarg1, HybridRNA jarg1_);
  public final static native long HybridRNA_GetRNA1(long jarg1, HybridRNA jarg1_);
  public final static native long HybridRNA_GetRNA2(long jarg1, HybridRNA jarg1_);
  public final static native int HybridRNA_GetErrorCode(long jarg1, HybridRNA jarg1_);
  public final static native String HybridRNA_GetErrorMessage(long jarg1, HybridRNA jarg1_, int jarg2);
  public final static native boolean HybridRNA_GetForbidIntramolecular(long jarg1, HybridRNA jarg1_);
  public final static native void HybridRNA_SetForbidIntramolecular(long jarg1, HybridRNA jarg1_, boolean jarg2);
  public final static native void HybridRNA_SetProgress(long jarg1, HybridRNA jarg1_, long jarg2, TProgressDialog jarg2_);
  public final static native void HybridRNA_StopProgress(long jarg1, HybridRNA jarg1_);
  public final static native void delete_HybridRNA(long jarg1);
  public final static native long SWIGHybridRNAUpcast(long jarg1);
}
