/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public class Oligowalk_object extends RNA {
  private long swigCPtr;

  protected Oligowalk_object(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Oligowalk_object obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      Oligowalk_objectProxyJNI.delete_Oligowalk_object(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public Oligowalk_object(String sequence) {
    this(Oligowalk_objectProxyJNI.new_Oligowalk_object__SWIG_0(sequence), true);
  }

  public Oligowalk_object(String filename, int type) {
    this(Oligowalk_objectProxyJNI.new_Oligowalk_object__SWIG_1(filename, type), true);
  }

  public Oligowalk_object(boolean IsRNA) {
    this(Oligowalk_objectProxyJNI.new_Oligowalk_object__SWIG_2(IsRNA), true);
  }

  public Oligowalk_object() {
    this(Oligowalk_objectProxyJNI.new_Oligowalk_object__SWIG_3(), true);
  }

  public int Oligowalk(int oligo_length, boolean isDNA, int option, double oligo_concentration, int usesub, int start, int stop) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_Oligowalk(swigCPtr, this, oligo_length, isDNA, option, oligo_concentration, usesub, start, stop);
  }

  public double GetBreakTargetDG(int index) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_GetBreakTargetDG(swigCPtr, this, index);
  }

  public double GetDuplexDG(int index) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_GetDuplexDG(swigCPtr, this, index);
  }

  public double GetOligoOligoDG(int index) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_GetOligoOligoDG(swigCPtr, this, index);
  }

  public double GetOligoSelfDG(int index) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_GetOligoSelfDG(swigCPtr, this, index);
  }

  public double GetOverallDG(int index) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_GetOverallDG(swigCPtr, this, index);
  }

  public double GetTm(int index) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_GetTm(swigCPtr, this, index);
  }

  public int WriteReport(String outputfilename, int oligo_length, boolean isDNA, int option, double oligo_concentration, int usesub, int start, int stop) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_WriteReport(swigCPtr, this, outputfilename, oligo_length, isDNA, option, oligo_concentration, usesub, start, stop);
  }

  public int OligoScreen(String infilename, String outfilename) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_OligoScreen(swigCPtr, this, infilename, outfilename);
  }

  public String GetErrorMessage(int error) {
    return Oligowalk_objectProxyJNI.Oligowalk_object_GetErrorMessage(swigCPtr, this, error);
  }

}
