/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

class Oligowalk_objectProxyJNI {
  public final static native long new_Oligowalk_object__SWIG_0(String jarg1);
  public final static native long new_Oligowalk_object__SWIG_1(String jarg1, int jarg2);
  public final static native long new_Oligowalk_object__SWIG_2(boolean jarg1);
  public final static native long new_Oligowalk_object__SWIG_3();
  public final static native int Oligowalk_object_Oligowalk(long jarg1, Oligowalk_object jarg1_, int jarg2, boolean jarg3, int jarg4, double jarg5, int jarg6, int jarg7, int jarg8);
  public final static native double Oligowalk_object_GetBreakTargetDG(long jarg1, Oligowalk_object jarg1_, int jarg2);
  public final static native double Oligowalk_object_GetDuplexDG(long jarg1, Oligowalk_object jarg1_, int jarg2);
  public final static native double Oligowalk_object_GetOligoOligoDG(long jarg1, Oligowalk_object jarg1_, int jarg2);
  public final static native double Oligowalk_object_GetOligoSelfDG(long jarg1, Oligowalk_object jarg1_, int jarg2);
  public final static native double Oligowalk_object_GetOverallDG(long jarg1, Oligowalk_object jarg1_, int jarg2);
  public final static native double Oligowalk_object_GetTm(long jarg1, Oligowalk_object jarg1_, int jarg2);
  public final static native int Oligowalk_object_WriteReport(long jarg1, Oligowalk_object jarg1_, String jarg2, int jarg3, boolean jarg4, int jarg5, double jarg6, int jarg7, int jarg8, int jarg9);
  public final static native int Oligowalk_object_OligoScreen(long jarg1, Oligowalk_object jarg1_, String jarg2, String jarg3);
  public final static native String Oligowalk_object_GetErrorMessage(long jarg1, Oligowalk_object jarg1_, int jarg2);
  public final static native void delete_Oligowalk_object(long jarg1);
  public final static native long SWIGOligowalk_objectUpcast(long jarg1);
}
