/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public class Postscript_Wrapper {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Postscript_Wrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Postscript_Wrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      PostscriptProxyJNI.delete_Postscript_Wrapper(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Postscript_Wrapper() {
    this(PostscriptProxyJNI.new_Postscript_Wrapper(), true);
  }

  public boolean plotDynalign1(DotPlotHandler handler) {
    return PostscriptProxyJNI.Postscript_Wrapper_plotDynalign1(swigCPtr, this, DotPlotHandler.getCPtr(handler), handler);
  }

  public boolean plotDynalign2(DotPlotHandler handler) {
    return PostscriptProxyJNI.Postscript_Wrapper_plotDynalign2(swigCPtr, this, DotPlotHandler.getCPtr(handler), handler);
  }

  public boolean plotEnergy(DotPlotHandler handler) {
    return PostscriptProxyJNI.Postscript_Wrapper_plotEnergy(swigCPtr, this, DotPlotHandler.getCPtr(handler), handler);
  }

  public boolean plotProbability(DotPlotHandler handler) {
    return PostscriptProxyJNI.Postscript_Wrapper_plotProbability(swigCPtr, this, DotPlotHandler.getCPtr(handler), handler);
  }

  public boolean structureCircular(String in, String out) {
    return PostscriptProxyJNI.Postscript_Wrapper_structureCircular(swigCPtr, this, in, out);
  }

  public boolean structureCircular_Probability(String in, String out, String file) {
    return PostscriptProxyJNI.Postscript_Wrapper_structureCircular_Probability(swigCPtr, this, in, out, file);
  }

  public boolean structureCircular_SHAPE(String in, String out, String file) {
    return PostscriptProxyJNI.Postscript_Wrapper_structureCircular_SHAPE(swigCPtr, this, in, out, file);
  }

  public boolean structureRadial(String in, String out) {
    return PostscriptProxyJNI.Postscript_Wrapper_structureRadial(swigCPtr, this, in, out);
  }

  public boolean structureRadial_Probability(String in, String out, String file) {
    return PostscriptProxyJNI.Postscript_Wrapper_structureRadial_Probability(swigCPtr, this, in, out, file);
  }

  public boolean structureRadial_SHAPE(String in, String out, String file) {
    return PostscriptProxyJNI.Postscript_Wrapper_structureRadial_SHAPE(swigCPtr, this, in, out, file);
  }

}
