/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public class ProgressMonitor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ProgressMonitor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProgressMonitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ProgressMonitorProxyJNI.delete_ProgressMonitor(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ProgressMonitor() {
    this(ProgressMonitorProxyJNI.new_ProgressMonitor(), true);
  }

  public int getMonitorProgress() {
    return ProgressMonitorProxyJNI.ProgressMonitor_getMonitorProgress(swigCPtr, this);
  }

  public void setMonitorProgress(int percent) {
    ProgressMonitorProxyJNI.ProgressMonitor_setMonitorProgress(swigCPtr, this, percent);
  }

}
