/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public class RNA extends Thermodynamics {
  private long swigCPtr;

  protected RNA(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RNA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      RNAProxyJNI.delete_RNA(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  private TProgressDialog dialogReference;
  private long getCPtrAndAddReference(TProgressDialog dialog) {
    dialogReference = dialog;
    return TProgressDialog.getCPtr(dialog);
  }

  public RNA(String sequence, boolean IsRNA) {
    this(RNAProxyJNI.new_RNA__SWIG_0(sequence, IsRNA), true);
  }

  public RNA(String sequence) {
    this(RNAProxyJNI.new_RNA__SWIG_1(sequence), true);
  }

  public RNA(String filename, int type, boolean IsRNA) {
    this(RNAProxyJNI.new_RNA__SWIG_2(filename, type, IsRNA), true);
  }

  public RNA(String filename, int type) {
    this(RNAProxyJNI.new_RNA__SWIG_3(filename, type), true);
  }

  public RNA(boolean IsRNA) {
    this(RNAProxyJNI.new_RNA__SWIG_4(IsRNA), true);
  }

  public RNA() {
    this(RNAProxyJNI.new_RNA__SWIG_5(), true);
  }

  public int GetErrorCode() {
    return RNAProxyJNI.RNA_GetErrorCode(swigCPtr, this);
  }

  public String GetErrorMessage(int error) {
    return RNAProxyJNI.RNA_GetErrorMessage(swigCPtr, this, error);
  }

  public String GetErrorMessageString(int error) {
    return RNAProxyJNI.RNA_GetErrorMessageString(swigCPtr, this, error);
  }

  public int SpecifyPair(int i, int j, int structurenumber) {
    return RNAProxyJNI.RNA_SpecifyPair__SWIG_0(swigCPtr, this, i, j, structurenumber);
  }

  public int SpecifyPair(int i, int j) {
    return RNAProxyJNI.RNA_SpecifyPair__SWIG_1(swigCPtr, this, i, j);
  }

  public int RemovePairs(int structurenumber) {
    return RNAProxyJNI.RNA_RemovePairs__SWIG_0(swigCPtr, this, structurenumber);
  }

  public int RemovePairs() {
    return RNAProxyJNI.RNA_RemovePairs__SWIG_1(swigCPtr, this);
  }

  public int RemoveBasePair(int i, int structurenumber) {
    return RNAProxyJNI.RNA_RemoveBasePair__SWIG_0(swigCPtr, this, i, structurenumber);
  }

  public int RemoveBasePair(int i) {
    return RNAProxyJNI.RNA_RemoveBasePair__SWIG_1(swigCPtr, this, i);
  }

  public double CalculateFreeEnergy(int structurenumber) {
    return RNAProxyJNI.RNA_CalculateFreeEnergy__SWIG_0(swigCPtr, this, structurenumber);
  }

  public double CalculateFreeEnergy() {
    return RNAProxyJNI.RNA_CalculateFreeEnergy__SWIG_1(swigCPtr, this);
  }

  public int WriteThermodynamicDetails(String filename) {
    return RNAProxyJNI.RNA_WriteThermodynamicDetails(swigCPtr, this, filename);
  }

  public int FoldSingleStrand(float percent, int maximumstructures, int window, String savefile, int maxinternalloopsize) {
    return RNAProxyJNI.RNA_FoldSingleStrand__SWIG_0(swigCPtr, this, percent, maximumstructures, window, savefile, maxinternalloopsize);
  }

  public int FoldSingleStrand(float percent, int maximumstructures, int window, String savefile) {
    return RNAProxyJNI.RNA_FoldSingleStrand__SWIG_1(swigCPtr, this, percent, maximumstructures, window, savefile);
  }

  public int FoldSingleStrand(float percent, int maximumstructures, int window) {
    return RNAProxyJNI.RNA_FoldSingleStrand__SWIG_2(swigCPtr, this, percent, maximumstructures, window);
  }

  public int GenerateAllSuboptimalStructures(float percent, double deltaG) {
    return RNAProxyJNI.RNA_GenerateAllSuboptimalStructures(swigCPtr, this, percent, deltaG);
  }

  public int MaximizeExpectedAccuracy(double maxPercent, int maxStructures, int window, double gamma) {
    return RNAProxyJNI.RNA_MaximizeExpectedAccuracy__SWIG_0(swigCPtr, this, maxPercent, maxStructures, window, gamma);
  }

  public int MaximizeExpectedAccuracy(double maxPercent, int maxStructures, int window) {
    return RNAProxyJNI.RNA_MaximizeExpectedAccuracy__SWIG_1(swigCPtr, this, maxPercent, maxStructures, window);
  }

  public int PartitionFunction(String savefile, double temperature) {
    return RNAProxyJNI.RNA_PartitionFunction__SWIG_0(swigCPtr, this, savefile, temperature);
  }

  public int PartitionFunction(String savefile) {
    return RNAProxyJNI.RNA_PartitionFunction__SWIG_1(swigCPtr, this, savefile);
  }

  public int PartitionFunction() {
    return RNAProxyJNI.RNA_PartitionFunction__SWIG_2(swigCPtr, this);
  }

  public int PredictProbablePairs(float probability) {
    return RNAProxyJNI.RNA_PredictProbablePairs__SWIG_0(swigCPtr, this, probability);
  }

  public int PredictProbablePairs() {
    return RNAProxyJNI.RNA_PredictProbablePairs__SWIG_1(swigCPtr, this);
  }

  public int ProbKnot(int iterations, int MinHelixLength) {
    return RNAProxyJNI.RNA_ProbKnot__SWIG_0(swigCPtr, this, iterations, MinHelixLength);
  }

  public int ProbKnot(int iterations) {
    return RNAProxyJNI.RNA_ProbKnot__SWIG_1(swigCPtr, this, iterations);
  }

  public int ProbKnot() {
    return RNAProxyJNI.RNA_ProbKnot__SWIG_2(swigCPtr, this);
  }

  public int ReFoldSingleStrand(float percent, int maximumstructures, int window) {
    return RNAProxyJNI.RNA_ReFoldSingleStrand(swigCPtr, this, percent, maximumstructures, window);
  }

  public int Stochastic(int structures, int seed) {
    return RNAProxyJNI.RNA_Stochastic__SWIG_0(swigCPtr, this, structures, seed);
  }

  public int Stochastic(int structures) {
    return RNAProxyJNI.RNA_Stochastic__SWIG_1(swigCPtr, this, structures);
  }

  public int ForceDoubleStranded(int i) {
    return RNAProxyJNI.RNA_ForceDoubleStranded(swigCPtr, this, i);
  }

  public int ForceFMNCleavage(int i) {
    return RNAProxyJNI.RNA_ForceFMNCleavage(swigCPtr, this, i);
  }

  public int ForceMaximumPairingDistance(int distance) {
    return RNAProxyJNI.RNA_ForceMaximumPairingDistance(swigCPtr, this, distance);
  }

  public int ForceModification(int i) {
    return RNAProxyJNI.RNA_ForceModification(swigCPtr, this, i);
  }

  public int ForcePair(int i, int j) {
    return RNAProxyJNI.RNA_ForcePair(swigCPtr, this, i, j);
  }

  public int ForceProhibitPair(int i, int j) {
    return RNAProxyJNI.RNA_ForceProhibitPair(swigCPtr, this, i, j);
  }

  public int ForceSingleStranded(int i) {
    return RNAProxyJNI.RNA_ForceSingleStranded(swigCPtr, this, i);
  }

  public int GetForcedDoubleStranded(int constraintnumber) {
    return RNAProxyJNI.RNA_GetForcedDoubleStranded(swigCPtr, this, constraintnumber);
  }

  public int GetForcedFMNCleavage(int constraintnumber) {
    return RNAProxyJNI.RNA_GetForcedFMNCleavage(swigCPtr, this, constraintnumber);
  }

  public int GetForcedModification(int constraintnumber) {
    return RNAProxyJNI.RNA_GetForcedModification(swigCPtr, this, constraintnumber);
  }

  public int GetForcedPair(int constraintnumber, boolean fiveprime) {
    return RNAProxyJNI.RNA_GetForcedPair(swigCPtr, this, constraintnumber, fiveprime);
  }

  public int GetForcedProhibitedPair(int constraintnumber, boolean fiveprime) {
    return RNAProxyJNI.RNA_GetForcedProhibitedPair(swigCPtr, this, constraintnumber, fiveprime);
  }

  public int GetForcedSingleStranded(int constraintnumber) {
    return RNAProxyJNI.RNA_GetForcedSingleStranded(swigCPtr, this, constraintnumber);
  }

  public int GetMaximumPairingDistance() {
    return RNAProxyJNI.RNA_GetMaximumPairingDistance(swigCPtr, this);
  }

  public int GetNumberOfForcedDoubleStranded() {
    return RNAProxyJNI.RNA_GetNumberOfForcedDoubleStranded(swigCPtr, this);
  }

  public int GetNumberOfForcedFMNCleavages() {
    return RNAProxyJNI.RNA_GetNumberOfForcedFMNCleavages(swigCPtr, this);
  }

  public int GetNumberOfForcedModifications() {
    return RNAProxyJNI.RNA_GetNumberOfForcedModifications(swigCPtr, this);
  }

  public int GetNumberOfForcedPairs() {
    return RNAProxyJNI.RNA_GetNumberOfForcedPairs(swigCPtr, this);
  }

  public int GetNumberOfForcedProhibitedPairs() {
    return RNAProxyJNI.RNA_GetNumberOfForcedProhibitedPairs(swigCPtr, this);
  }

  public int GetNumberOfForcedSingleStranded() {
    return RNAProxyJNI.RNA_GetNumberOfForcedSingleStranded(swigCPtr, this);
  }

  public int ReadConstraints(String filename) {
    return RNAProxyJNI.RNA_ReadConstraints(swigCPtr, this, filename);
  }

  public int ReadSHAPE(String filename, double parameter1, double parameter2, boolean IsPseudoEnergy) {
    return RNAProxyJNI.RNA_ReadSHAPE__SWIG_0(swigCPtr, this, filename, parameter1, parameter2, IsPseudoEnergy);
  }

  public int ReadSHAPE(String filename, double parameter1, double parameter2) {
    return RNAProxyJNI.RNA_ReadSHAPE__SWIG_1(swigCPtr, this, filename, parameter1, parameter2);
  }

  public int ReadSHAPE(String filename, double parameter1, double parameter2, double ssm, double ssb) {
    return RNAProxyJNI.RNA_ReadSHAPE__SWIG_2(swigCPtr, this, filename, parameter1, parameter2, ssm, ssb);
  }

  public int ReadDSO(String filename) {
    return RNAProxyJNI.RNA_ReadDSO(swigCPtr, this, filename);
  }

  public int ReadSSO(String filename) {
    return RNAProxyJNI.RNA_ReadSSO(swigCPtr, this, filename);
  }

  public void RemoveConstraints() {
    RNAProxyJNI.RNA_RemoveConstraints(swigCPtr, this);
  }

  public int WriteConstraints(String filename) {
    return RNAProxyJNI.RNA_WriteConstraints(swigCPtr, this, filename);
  }

  public int AddComment(String comment, int structurenumber) {
    return RNAProxyJNI.RNA_AddComment__SWIG_0(swigCPtr, this, comment, structurenumber);
  }

  public int AddComment(String comment) {
    return RNAProxyJNI.RNA_AddComment__SWIG_1(swigCPtr, this, comment);
  }

  public int WriteCt(String filename) {
    return RNAProxyJNI.RNA_WriteCt(swigCPtr, this, filename);
  }

  public int WriteDotBracket(String filename) {
    return RNAProxyJNI.RNA_WriteDotBracket(swigCPtr, this, filename);
  }

  public int BreakPseudoknot(boolean minimum_energy) {
    return RNAProxyJNI.RNA_BreakPseudoknot__SWIG_0(swigCPtr, this, minimum_energy);
  }

  public int BreakPseudoknot() {
    return RNAProxyJNI.RNA_BreakPseudoknot__SWIG_1(swigCPtr, this);
  }

  public boolean ContainsPseudoknot(int structurenumber) {
    return RNAProxyJNI.RNA_ContainsPseudoknot(swigCPtr, this, structurenumber);
  }

  public double GetEnsembleEnergy() {
    return RNAProxyJNI.RNA_GetEnsembleEnergy(swigCPtr, this);
  }

  public double GetFreeEnergy(int structurenumber) {
    return RNAProxyJNI.RNA_GetFreeEnergy(swigCPtr, this, structurenumber);
  }

  public int GetPair(int i, int structurenumber) {
    return RNAProxyJNI.RNA_GetPair__SWIG_0(swigCPtr, this, i, structurenumber);
  }

  public int GetPair(int i) {
    return RNAProxyJNI.RNA_GetPair__SWIG_1(swigCPtr, this, i);
  }

  public double GetPairEnergy(int i, int j) {
    return RNAProxyJNI.RNA_GetPairEnergy(swigCPtr, this, i, j);
  }

  public double GetPairProbability(int i, int j) {
    return RNAProxyJNI.RNA_GetPairProbability(swigCPtr, this, i, j);
  }

  public int GetStructureNumber() {
    return RNAProxyJNI.RNA_GetStructureNumber(swigCPtr, this);
  }

  public int DetermineDrawingCoordinates(int height, int width, int structurenumber) {
    return RNAProxyJNI.RNA_DetermineDrawingCoordinates__SWIG_0(swigCPtr, this, height, width, structurenumber);
  }

  public int DetermineDrawingCoordinates(int height, int width) {
    return RNAProxyJNI.RNA_DetermineDrawingCoordinates__SWIG_1(swigCPtr, this, height, width);
  }

  public String GetCommentString(int structurenumber) {
    return RNAProxyJNI.RNA_GetCommentString__SWIG_0(swigCPtr, this, structurenumber);
  }

  public String GetCommentString() {
    return RNAProxyJNI.RNA_GetCommentString__SWIG_1(swigCPtr, this);
  }

  public int GetNucleotideXCoordinate(int i) {
    return RNAProxyJNI.RNA_GetNucleotideXCoordinate(swigCPtr, this, i);
  }

  public int GetNucleotideYCoordinate(int i) {
    return RNAProxyJNI.RNA_GetNucleotideYCoordinate(swigCPtr, this, i);
  }

  public int GetLabelXCoordinate(int i) {
    return RNAProxyJNI.RNA_GetLabelXCoordinate(swigCPtr, this, i);
  }

  public int GetLabelYCoordinate(int i) {
    return RNAProxyJNI.RNA_GetLabelYCoordinate(swigCPtr, this, i);
  }

  public char GetNucleotide(int i) {
    return RNAProxyJNI.RNA_GetNucleotide(swigCPtr, this, i);
  }

  public int GetSequenceLength() {
    return RNAProxyJNI.RNA_GetSequenceLength(swigCPtr, this);
  }

  public boolean GetBackboneType() {
    return RNAProxyJNI.RNA_GetBackboneType(swigCPtr, this);
  }

  public void SetProgress(TProgressDialog Progress) {
    RNAProxyJNI.RNA_SetProgress(swigCPtr, this, getCPtrAndAddReference(Progress), Progress);
  }

  public void StopProgress() {
    RNAProxyJNI.RNA_StopProgress(swigCPtr, this);
  }

  public TProgressDialog GetProgress() {
    long cPtr = RNAProxyJNI.RNA_GetProgress(swigCPtr, this);
    return (cPtr == 0) ? null : new TProgressDialog(cPtr, false);
  }

}
