/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

class RNAProxyJNI {
  public final static native long new_RNA__SWIG_0(String jarg1, boolean jarg2);
  public final static native long new_RNA__SWIG_1(String jarg1);
  public final static native long new_RNA__SWIG_2(String jarg1, int jarg2, boolean jarg3);
  public final static native long new_RNA__SWIG_3(String jarg1, int jarg2);
  public final static native long new_RNA__SWIG_4(boolean jarg1);
  public final static native long new_RNA__SWIG_5();
  public final static native int RNA_GetErrorCode(long jarg1, RNA jarg1_);
  public final static native String RNA_GetErrorMessage(long jarg1, RNA jarg1_, int jarg2);
  public final static native String RNA_GetErrorMessageString(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_SpecifyPair__SWIG_0(long jarg1, RNA jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native int RNA_SpecifyPair__SWIG_1(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native int RNA_RemovePairs__SWIG_0(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_RemovePairs__SWIG_1(long jarg1, RNA jarg1_);
  public final static native int RNA_RemoveBasePair__SWIG_0(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native int RNA_RemoveBasePair__SWIG_1(long jarg1, RNA jarg1_, int jarg2);
  public final static native double RNA_CalculateFreeEnergy__SWIG_0(long jarg1, RNA jarg1_, int jarg2);
  public final static native double RNA_CalculateFreeEnergy__SWIG_1(long jarg1, RNA jarg1_);
  public final static native int RNA_WriteThermodynamicDetails(long jarg1, RNA jarg1_, String jarg2);
  public final static native int RNA_FoldSingleStrand__SWIG_0(long jarg1, RNA jarg1_, float jarg2, int jarg3, int jarg4, String jarg5, int jarg6);
  public final static native int RNA_FoldSingleStrand__SWIG_1(long jarg1, RNA jarg1_, float jarg2, int jarg3, int jarg4, String jarg5);
  public final static native int RNA_FoldSingleStrand__SWIG_2(long jarg1, RNA jarg1_, float jarg2, int jarg3, int jarg4);
  public final static native int RNA_GenerateAllSuboptimalStructures(long jarg1, RNA jarg1_, float jarg2, double jarg3);
  public final static native int RNA_MaximizeExpectedAccuracy__SWIG_0(long jarg1, RNA jarg1_, double jarg2, int jarg3, int jarg4, double jarg5);
  public final static native int RNA_MaximizeExpectedAccuracy__SWIG_1(long jarg1, RNA jarg1_, double jarg2, int jarg3, int jarg4);
  public final static native int RNA_PartitionFunction__SWIG_0(long jarg1, RNA jarg1_, String jarg2, double jarg3);
  public final static native int RNA_PartitionFunction__SWIG_1(long jarg1, RNA jarg1_, String jarg2);
  public final static native int RNA_PartitionFunction__SWIG_2(long jarg1, RNA jarg1_);
  public final static native int RNA_PredictProbablePairs__SWIG_0(long jarg1, RNA jarg1_, float jarg2);
  public final static native int RNA_PredictProbablePairs__SWIG_1(long jarg1, RNA jarg1_);
  public final static native int RNA_ProbKnot__SWIG_0(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native int RNA_ProbKnot__SWIG_1(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_ProbKnot__SWIG_2(long jarg1, RNA jarg1_);
  public final static native int RNA_ReFoldSingleStrand(long jarg1, RNA jarg1_, float jarg2, int jarg3, int jarg4);
  public final static native int RNA_Stochastic__SWIG_0(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native int RNA_Stochastic__SWIG_1(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_ForceDoubleStranded(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_ForceFMNCleavage(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_ForceMaximumPairingDistance(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_ForceModification(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_ForcePair(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native int RNA_ForceProhibitPair(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native int RNA_ForceSingleStranded(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetForcedDoubleStranded(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetForcedFMNCleavage(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetForcedModification(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetForcedPair(long jarg1, RNA jarg1_, int jarg2, boolean jarg3);
  public final static native int RNA_GetForcedProhibitedPair(long jarg1, RNA jarg1_, int jarg2, boolean jarg3);
  public final static native int RNA_GetForcedSingleStranded(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetMaximumPairingDistance(long jarg1, RNA jarg1_);
  public final static native int RNA_GetNumberOfForcedDoubleStranded(long jarg1, RNA jarg1_);
  public final static native int RNA_GetNumberOfForcedFMNCleavages(long jarg1, RNA jarg1_);
  public final static native int RNA_GetNumberOfForcedModifications(long jarg1, RNA jarg1_);
  public final static native int RNA_GetNumberOfForcedPairs(long jarg1, RNA jarg1_);
  public final static native int RNA_GetNumberOfForcedProhibitedPairs(long jarg1, RNA jarg1_);
  public final static native int RNA_GetNumberOfForcedSingleStranded(long jarg1, RNA jarg1_);
  public final static native int RNA_ReadConstraints(long jarg1, RNA jarg1_, String jarg2);
  public final static native int RNA_ReadSHAPE__SWIG_0(long jarg1, RNA jarg1_, String jarg2, double jarg3, double jarg4, boolean jarg5);
  public final static native int RNA_ReadSHAPE__SWIG_1(long jarg1, RNA jarg1_, String jarg2, double jarg3, double jarg4);
  public final static native int RNA_ReadSHAPE__SWIG_2(long jarg1, RNA jarg1_, String jarg2, double jarg3, double jarg4, double jarg5, double jarg6);
  public final static native int RNA_ReadDSO(long jarg1, RNA jarg1_, String jarg2);
  public final static native int RNA_ReadSSO(long jarg1, RNA jarg1_, String jarg2);
  public final static native void RNA_RemoveConstraints(long jarg1, RNA jarg1_);
  public final static native int RNA_WriteConstraints(long jarg1, RNA jarg1_, String jarg2);
  public final static native int RNA_AddComment__SWIG_0(long jarg1, RNA jarg1_, String jarg2, int jarg3);
  public final static native int RNA_AddComment__SWIG_1(long jarg1, RNA jarg1_, String jarg2);
  public final static native int RNA_WriteCt(long jarg1, RNA jarg1_, String jarg2);
  public final static native int RNA_WriteDotBracket(long jarg1, RNA jarg1_, String jarg2);
  public final static native int RNA_BreakPseudoknot__SWIG_0(long jarg1, RNA jarg1_, boolean jarg2);
  public final static native int RNA_BreakPseudoknot__SWIG_1(long jarg1, RNA jarg1_);
  public final static native boolean RNA_ContainsPseudoknot(long jarg1, RNA jarg1_, int jarg2);
  public final static native double RNA_GetEnsembleEnergy(long jarg1, RNA jarg1_);
  public final static native double RNA_GetFreeEnergy(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetPair__SWIG_0(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native int RNA_GetPair__SWIG_1(long jarg1, RNA jarg1_, int jarg2);
  public final static native double RNA_GetPairEnergy(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native double RNA_GetPairProbability(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native int RNA_GetStructureNumber(long jarg1, RNA jarg1_);
  public final static native int RNA_DetermineDrawingCoordinates__SWIG_0(long jarg1, RNA jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native int RNA_DetermineDrawingCoordinates__SWIG_1(long jarg1, RNA jarg1_, int jarg2, int jarg3);
  public final static native String RNA_GetCommentString__SWIG_0(long jarg1, RNA jarg1_, int jarg2);
  public final static native String RNA_GetCommentString__SWIG_1(long jarg1, RNA jarg1_);
  public final static native int RNA_GetNucleotideXCoordinate(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetNucleotideYCoordinate(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetLabelXCoordinate(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetLabelYCoordinate(long jarg1, RNA jarg1_, int jarg2);
  public final static native char RNA_GetNucleotide(long jarg1, RNA jarg1_, int jarg2);
  public final static native int RNA_GetSequenceLength(long jarg1, RNA jarg1_);
  public final static native boolean RNA_GetBackboneType(long jarg1, RNA jarg1_);
  public final static native void RNA_SetProgress(long jarg1, RNA jarg1_, long jarg2, TProgressDialog jarg2_);
  public final static native void RNA_StopProgress(long jarg1, RNA jarg1_);
  public final static native long RNA_GetProgress(long jarg1, RNA jarg1_);
  public final static native void delete_RNA(long jarg1);
  public final static native long SWIGRNAUpcast(long jarg1);
}
