/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public class Thermodynamics {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Thermodynamics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Thermodynamics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ThermodynamicsProxyJNI.delete_Thermodynamics(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Thermodynamics(boolean ISRNA) {
    this(ThermodynamicsProxyJNI.new_Thermodynamics__SWIG_0(ISRNA), true);
  }

  public Thermodynamics() {
    this(ThermodynamicsProxyJNI.new_Thermodynamics__SWIG_1(), true);
  }

  public int SetTemperature(double temperature) {
    return ThermodynamicsProxyJNI.Thermodynamics_SetTemperature(swigCPtr, this, temperature);
  }

  public double GetTemperature() {
    return ThermodynamicsProxyJNI.Thermodynamics_GetTemperature(swigCPtr, this);
  }

  public int ReadThermodynamic() {
    return ThermodynamicsProxyJNI.Thermodynamics_ReadThermodynamic(swigCPtr, this);
  }

  public void setIsrna(boolean value) {
    ThermodynamicsProxyJNI.Thermodynamics_isrna_set(swigCPtr, this, value);
  }

  public boolean getIsrna() {
    return ThermodynamicsProxyJNI.Thermodynamics_isrna_get(swigCPtr, this);
  }

}
