/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

class TProgressDialogProxyJNI {
  public final static native long new_TProgressDialog(long jarg1, ProgressMonitor jarg1_);
  public final static native void TProgressDialog_update(long jarg1, TProgressDialog jarg1_, int jarg2);
  public final static native void delete_TProgressDialog(long jarg1);
}
