/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

class TwoRNAProxyJNI {
  public final static native int COMPOUNDMESSAGELENGTH_get();
  public final static native long new_TwoRNA__SWIG_0(String jarg1, String jarg2, boolean jarg3);
  public final static native long new_TwoRNA__SWIG_1(String jarg1, String jarg2);
  public final static native long new_TwoRNA__SWIG_2(String jarg1, int jarg2, String jarg3, int jarg4, boolean jarg5);
  public final static native long new_TwoRNA__SWIG_3(String jarg1, int jarg2, String jarg3, int jarg4);
  public final static native long new_TwoRNA__SWIG_4();
  public final static native int TwoRNA_GetErrorCode(long jarg1, TwoRNA jarg1_);
  public final static native String TwoRNA_GetErrorMessage(long jarg1, TwoRNA jarg1_, int jarg2);
  public final static native String TwoRNA_GetErrorMessageString(long jarg1, TwoRNA jarg1_, int jarg2);
  public final static native long TwoRNA_GetRNA1(long jarg1, TwoRNA jarg1_);
  public final static native long TwoRNA_GetRNA2(long jarg1, TwoRNA jarg1_);
  public final static native void delete_TwoRNA(long jarg1);
  public final static native void TwoRNA_compoundmessage_set(long jarg1, TwoRNA jarg1_, String jarg2);
  public final static native String TwoRNA_compoundmessage_get(long jarg1, TwoRNA jarg1_);
}
