/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public class TwoRNA {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TwoRNA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TwoRNA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      TwoRNAProxyJNI.delete_TwoRNA(swigCPtr);
    }
    swigCPtr = 0;
  }

  public TwoRNA(String sequence1, String sequence2, boolean IsRNA) {
    this(TwoRNAProxyJNI.new_TwoRNA__SWIG_0(sequence1, sequence2, IsRNA), true);
  }

  public TwoRNA(String sequence1, String sequence2) {
    this(TwoRNAProxyJNI.new_TwoRNA__SWIG_1(sequence1, sequence2), true);
  }

  public TwoRNA(String filename1, int type1, String filename2, int type2, boolean IsRNA) {
    this(TwoRNAProxyJNI.new_TwoRNA__SWIG_2(filename1, type1, filename2, type2, IsRNA), true);
  }

  public TwoRNA(String filename1, int type1, String filename2, int type2) {
    this(TwoRNAProxyJNI.new_TwoRNA__SWIG_3(filename1, type1, filename2, type2), true);
  }

  public TwoRNA() {
    this(TwoRNAProxyJNI.new_TwoRNA__SWIG_4(), true);
  }

  public int GetErrorCode() {
    return TwoRNAProxyJNI.TwoRNA_GetErrorCode(swigCPtr, this);
  }

  public String GetErrorMessage(int error) {
    return TwoRNAProxyJNI.TwoRNA_GetErrorMessage(swigCPtr, this, error);
  }

  public String GetErrorMessageString(int error) {
    return TwoRNAProxyJNI.TwoRNA_GetErrorMessageString(swigCPtr, this, error);
  }

  public RNA GetRNA1() {
    long cPtr = TwoRNAProxyJNI.TwoRNA_GetRNA1(swigCPtr, this);
    return (cPtr == 0) ? null : new RNA(cPtr, false);
  }

  public RNA GetRNA2() {
    long cPtr = TwoRNAProxyJNI.TwoRNA_GetRNA2(swigCPtr, this);
    return (cPtr == 0) ? null : new RNA(cPtr, false);
  }

  public void setCompoundmessage(String value) {
    TwoRNAProxyJNI.TwoRNA_compoundmessage_set(swigCPtr, this, value);
  }

  public String getCompoundmessage() {
    return TwoRNAProxyJNI.TwoRNA_compoundmessage_get(swigCPtr, this);
  }

}
