/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package source;

public interface TwoRNAProxyConstants {
  public final static int COMPOUNDMESSAGELENGTH = TwoRNAProxyJNI.COMPOUNDMESSAGELENGTH_get();
}
