/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "../../src/DotPlotHandler.h"


#include <string>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_source_DotPlotHandlerProxyJNI_new_1DotPlotHandler(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  std::string arg1 ;
  std::string arg2 ;
  DotPlotHandler *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  if(!jarg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
    return 0;
  } 
  const char *arg1_pstr = (const char *)jenv->GetStringUTFChars(jarg1, 0); 
  if (!arg1_pstr) return 0;
  (&arg1)->assign(arg1_pstr);
  jenv->ReleaseStringUTFChars(jarg1, arg1_pstr); 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = (DotPlotHandler *)new DotPlotHandler(arg1,arg2);
  *(DotPlotHandler **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_delete_1DotPlotHandler(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DotPlotHandler **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jstring JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getColorAsPostscript(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  jstring jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  int arg2 ;
  int arg3 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (arg1)->getColorAsPostscript(arg2,arg3);
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getColorAsRGB(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  jstring jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  int arg2 ;
  int arg3 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (arg1)->getColorAsRGB(arg2,arg3);
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getEntries(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  result = (int)(arg1)->getEntries();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getInfoString(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  result = (arg1)->getInfoString();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getInputFile(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  result = (arg1)->getInputFile();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getMaximum(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  result = (double)(arg1)->getMaximum();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getMinimum(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  result = (double)(arg1)->getMinimum();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getOutputFile(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  result = (arg1)->getOutputFile();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jchar JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getPlotType(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jchar jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  result = (char)(arg1)->getPlotType();
  jresult = (jchar)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1getValue(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  jdouble jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  int arg2 ;
  int arg3 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (double)(arg1)->getValue(arg2,arg3);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1isError(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  result = (bool)(arg1)->isError();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1readDynalignSeq1Data(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  (arg1)->readDynalignSeq1Data();
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1readDynalignSeq2Data(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  (arg1)->readDynalignSeq2Data();
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1readFoldingData(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  (arg1)->readFoldingData();
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1readPartitionData(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  (arg1)->readPartitionData();
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1readTextData(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  (arg1)->readTextData();
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1resetRange(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  (arg1)->resetRange();
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1setEntries(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  arg2 = (int)jarg2; 
  (arg1)->setEntries(arg2);
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1setMaximum(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  arg2 = (double)jarg2; 
  (arg1)->setMaximum(arg2);
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1setMinimum(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  arg2 = (double)jarg2; 
  (arg1)->setMinimum(arg2);
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1setPlotType(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jchar jarg2) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  arg2 = (char)jarg2; 
  (arg1)->setPlotType(arg2);
}


SWIGEXPORT void JNICALL Java_source_DotPlotHandlerProxyJNI_DotPlotHandler_1writePlotFile(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DotPlotHandler *arg1 = (DotPlotHandler *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DotPlotHandler **)&jarg1; 
  (arg1)->writePlotFile();
}


#ifdef __cplusplus
}
#endif

