/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "../../RNA_class/Dynalign_object.h"


#include <string>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_source_Dynalign_1objectProxyJNI_new_1Dynalign_1object_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Dynalign_object *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Dynalign_object *)new Dynalign_object();
  *(Dynalign_object **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_source_Dynalign_1objectProxyJNI_new_1Dynalign_1object_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jboolean jarg3) {
  jlong jresult = 0 ;
  char *arg1 ;
  char *arg2 ;
  bool arg3 ;
  Dynalign_object *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = jarg3 ? true : false; 
  result = (Dynalign_object *)new Dynalign_object((char const (*))arg1,(char const (*))arg2,arg3);
  *(Dynalign_object **)&jresult = result; 
  
  
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_source_Dynalign_1objectProxyJNI_new_1Dynalign_1object_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  char *arg1 ;
  char *arg2 ;
  Dynalign_object *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = (Dynalign_object *)new Dynalign_object((char const (*))arg1,(char const (*))arg2);
  *(Dynalign_object **)&jresult = result; 
  
  
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_source_Dynalign_1objectProxyJNI_new_1Dynalign_1object_1_1SWIG_13(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jstring jarg3, jint jarg4, jboolean jarg5) {
  jlong jresult = 0 ;
  char *arg1 ;
  int arg2 ;
  char *arg3 ;
  int arg4 ;
  bool arg5 ;
  Dynalign_object *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (int)jarg4; 
  arg5 = jarg5 ? true : false; 
  result = (Dynalign_object *)new Dynalign_object((char const (*))arg1,arg2,(char const (*))arg3,arg4,arg5);
  *(Dynalign_object **)&jresult = result; 
  
  
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_source_Dynalign_1objectProxyJNI_new_1Dynalign_1object_1_1SWIG_14(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jstring jarg3, jint jarg4) {
  jlong jresult = 0 ;
  char *arg1 ;
  int arg2 ;
  char *arg3 ;
  int arg4 ;
  Dynalign_object *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (int)jarg4; 
  result = (Dynalign_object *)new Dynalign_object((char const (*))arg1,arg2,(char const (*))arg3,arg4);
  *(Dynalign_object **)&jresult = result; 
  
  
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_source_Dynalign_1objectProxyJNI_new_1Dynalign_1object_1_1SWIG_15(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 ;
  Dynalign_object *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  result = (Dynalign_object *)new Dynalign_object((char const (*))arg1);
  *(Dynalign_object **)&jresult = result; 
  
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_source_Dynalign_1objectProxyJNI_new_1Dynalign_1object_1_1SWIG_16(JNIEnv *jenv, jclass jcls, jstring jarg1, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  Dynalign_object *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  result = (Dynalign_object *)new Dynalign_object((char const *)arg1,arg2,arg3,arg4,arg5);
  *(Dynalign_object **)&jresult = result; 
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jfloat jarg7, jboolean jarg8, jstring jarg9, jboolean jarg10, jshort jarg11, jboolean jarg12, jshort jarg13, jint jarg14, jshort jarg15) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  float arg7 ;
  bool arg8 ;
  char *arg9 ;
  bool arg10 ;
  short arg11 ;
  bool arg12 ;
  short arg13 ;
  int arg14 ;
  short arg15 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (float)jarg7; 
  arg8 = jarg8 ? true : false; 
  arg9 = 0;
  if (jarg9) {
    arg9 = (char *)jenv->GetStringUTFChars(jarg9, 0);
    if (!arg9) return 0;
  }
  arg10 = jarg10 ? true : false; 
  arg11 = (short)jarg11; 
  arg12 = jarg12 ? true : false; 
  arg13 = (short)jarg13; 
  arg14 = (int)jarg14; 
  arg15 = (short)jarg15; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6,arg7,arg8,(char const (*))arg9,arg10,arg11,arg12,arg13,arg14,arg15);
  jresult = (jint)result; 
  
  if (arg9) jenv->ReleaseStringUTFChars(jarg9, (const char *)arg9);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jfloat jarg7, jboolean jarg8, jstring jarg9, jboolean jarg10, jshort jarg11, jboolean jarg12, jshort jarg13, jint jarg14) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  float arg7 ;
  bool arg8 ;
  char *arg9 ;
  bool arg10 ;
  short arg11 ;
  bool arg12 ;
  short arg13 ;
  int arg14 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (float)jarg7; 
  arg8 = jarg8 ? true : false; 
  arg9 = 0;
  if (jarg9) {
    arg9 = (char *)jenv->GetStringUTFChars(jarg9, 0);
    if (!arg9) return 0;
  }
  arg10 = jarg10 ? true : false; 
  arg11 = (short)jarg11; 
  arg12 = jarg12 ? true : false; 
  arg13 = (short)jarg13; 
  arg14 = (int)jarg14; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6,arg7,arg8,(char const (*))arg9,arg10,arg11,arg12,arg13,arg14);
  jresult = (jint)result; 
  
  if (arg9) jenv->ReleaseStringUTFChars(jarg9, (const char *)arg9);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jfloat jarg7, jboolean jarg8, jstring jarg9, jboolean jarg10, jshort jarg11, jboolean jarg12, jshort jarg13) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  float arg7 ;
  bool arg8 ;
  char *arg9 ;
  bool arg10 ;
  short arg11 ;
  bool arg12 ;
  short arg13 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (float)jarg7; 
  arg8 = jarg8 ? true : false; 
  arg9 = 0;
  if (jarg9) {
    arg9 = (char *)jenv->GetStringUTFChars(jarg9, 0);
    if (!arg9) return 0;
  }
  arg10 = jarg10 ? true : false; 
  arg11 = (short)jarg11; 
  arg12 = jarg12 ? true : false; 
  arg13 = (short)jarg13; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6,arg7,arg8,(char const (*))arg9,arg10,arg11,arg12,arg13);
  jresult = (jint)result; 
  
  if (arg9) jenv->ReleaseStringUTFChars(jarg9, (const char *)arg9);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_13(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jfloat jarg7, jboolean jarg8, jstring jarg9, jboolean jarg10, jshort jarg11, jboolean jarg12) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  float arg7 ;
  bool arg8 ;
  char *arg9 ;
  bool arg10 ;
  short arg11 ;
  bool arg12 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (float)jarg7; 
  arg8 = jarg8 ? true : false; 
  arg9 = 0;
  if (jarg9) {
    arg9 = (char *)jenv->GetStringUTFChars(jarg9, 0);
    if (!arg9) return 0;
  }
  arg10 = jarg10 ? true : false; 
  arg11 = (short)jarg11; 
  arg12 = jarg12 ? true : false; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6,arg7,arg8,(char const (*))arg9,arg10,arg11,arg12);
  jresult = (jint)result; 
  
  if (arg9) jenv->ReleaseStringUTFChars(jarg9, (const char *)arg9);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_14(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jfloat jarg7, jboolean jarg8, jstring jarg9, jboolean jarg10, jshort jarg11) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  float arg7 ;
  bool arg8 ;
  char *arg9 ;
  bool arg10 ;
  short arg11 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (float)jarg7; 
  arg8 = jarg8 ? true : false; 
  arg9 = 0;
  if (jarg9) {
    arg9 = (char *)jenv->GetStringUTFChars(jarg9, 0);
    if (!arg9) return 0;
  }
  arg10 = jarg10 ? true : false; 
  arg11 = (short)jarg11; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6,arg7,arg8,(char const (*))arg9,arg10,arg11);
  jresult = (jint)result; 
  
  if (arg9) jenv->ReleaseStringUTFChars(jarg9, (const char *)arg9);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_15(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jfloat jarg7, jboolean jarg8, jstring jarg9, jboolean jarg10) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  float arg7 ;
  bool arg8 ;
  char *arg9 ;
  bool arg10 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (float)jarg7; 
  arg8 = jarg8 ? true : false; 
  arg9 = 0;
  if (jarg9) {
    arg9 = (char *)jenv->GetStringUTFChars(jarg9, 0);
    if (!arg9) return 0;
  }
  arg10 = jarg10 ? true : false; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6,arg7,arg8,(char const (*))arg9,arg10);
  jresult = (jint)result; 
  
  if (arg9) jenv->ReleaseStringUTFChars(jarg9, (const char *)arg9);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_16(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jfloat jarg7, jboolean jarg8, jstring jarg9) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  float arg7 ;
  bool arg8 ;
  char *arg9 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (float)jarg7; 
  arg8 = jarg8 ? true : false; 
  arg9 = 0;
  if (jarg9) {
    arg9 = (char *)jenv->GetStringUTFChars(jarg9, 0);
    if (!arg9) return 0;
  }
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6,arg7,arg8,(char const (*))arg9);
  jresult = (jint)result; 
  
  if (arg9) jenv->ReleaseStringUTFChars(jarg9, (const char *)arg9);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_17(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jfloat jarg7, jboolean jarg8) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  float arg7 ;
  bool arg8 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (float)jarg7; 
  arg8 = jarg8 ? true : false; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_18(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6, jfloat jarg7) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  float arg7 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  arg7 = (float)jarg7; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_19(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5, jshort jarg6) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  arg6 = (short)jarg6; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Dynalign_1_1SWIG_110(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4, jshort jarg5) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (short)jarg2; 
  arg3 = (short)jarg3; 
  arg4 = (short)jarg4; 
  arg5 = (short)jarg5; 
  result = (int)(arg1)->Dynalign(arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1WriteAlignment(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  char *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  (arg1)->WriteAlignment((char const (*))arg2);
  
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1ForceAlignment(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  int arg2 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (int)(arg1)->ForceAlignment(arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1GetForcedAlignment(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  int arg2 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (int)(arg1)->GetForcedAlignment(arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1ReadAlignmentConstraints(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  char *arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)(arg1)->ReadAlignmentConstraints((char const (*))arg2);
  jresult = (jint)result; 
  
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Templatefromct(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  char *arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)(arg1)->Templatefromct((char const (*))arg2);
  jresult = (jint)result; 
  
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1Templatefromdsv(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jfloat jarg3) {
  jint jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  char *arg2 ;
  float arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (float)jarg3; 
  result = (int)(arg1)->Templatefromdsv((char const (*))arg2,arg3);
  jresult = (jint)result; 
  
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1GetBestPairEnergy(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3, jint jarg4) {
  jdouble jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (double)(arg1)->GetBestPairEnergy(arg2,arg3,arg4);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1GetLowestEnergy(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  result = (double)(arg1)->GetLowestEnergy();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1GetErrorMessage(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jstring jresult = 0 ;
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  int arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)(arg1)->GetErrorMessage(arg2);
  if(result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1SetProgress(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  TProgressDialog *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Dynalign_object **)&jarg1; 
  arg2 = *(TProgressDialog **)&jarg2;
  if(!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "TProgressDialog & reference is null");
    return ;
  } 
  (arg1)->SetProgress(*arg2);
}


SWIGEXPORT void JNICALL Java_source_Dynalign_1objectProxyJNI_Dynalign_1object_1StopProgress(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dynalign_object **)&jarg1; 
  (arg1)->StopProgress();
}


SWIGEXPORT void JNICALL Java_source_Dynalign_1objectProxyJNI_delete_1Dynalign_1object(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Dynalign_object *arg1 = (Dynalign_object *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Dynalign_object **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_source_Dynalign_1objectProxyJNI_SWIGDynalign_1objectUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(TwoRNA **)&baseptr = *(Dynalign_object **)&jarg1;
    return baseptr;
}

#ifdef __cplusplus
}
#endif

